In [1]:
import numpy as np

In [2]:
zero_v = np.zeros(5)

In [4]:
zero_m = np.zeros((5,3))

In [5]:
zero_m

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
x = np.array([1,2,3])

In [7]:
y = np.array([2,4,6])

In [9]:
z = np.array([[5,6] , [7,8] , [2 , 3]])

In [10]:
z

array([[5, 6],
       [7, 8],
       [2, 3]])

In [11]:
type(z)

numpy.ndarray

In [16]:
z1 = np.transpose(z)
print(z1)

[[5 7 2]
 [6 8 3]]


In [19]:
x = np.array([[3,6],[5,7]])
y = x.transpose()
print(y)

[[3 5]
 [6 7]]


In [20]:
x = np.array([1,2,3])
y = np.array([2,4,6])

In [21]:
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[2,4,6],[8,10,12]])

In [22]:
x[2]

3

In [24]:
x[0:2]

array([1, 2])

In [25]:
z = x +y

In [26]:
z

array([3, 6, 9])

In [34]:
X

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
X[1]

array([4, 5, 6])

In [39]:
a = np.array([1,2])
b = np.array([3,4,5])
a + b

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [40]:
z1 = np.array([1,3,5,7,9])

In [41]:
z2 = z1 + 1

In [42]:
ind = [0,2,3]

In [43]:
z1[ind]

array([1, 5, 7])

In [44]:
z1[ind] < 2

array([ True, False, False])

In [45]:
z1

array([1, 3, 5, 7, 9])

In [46]:
w = z1[0:3]

In [47]:
w

array([1, 3, 5])

In [48]:
w[0]=3

In [49]:
z1

array([3, 3, 5, 7, 9])

In [50]:
z1[0]=1

In [51]:
z1

array([1, 3, 5, 7, 9])

In [53]:
ind = np.array([0,1,2])

In [54]:
ind

array([0, 1, 2])

In [55]:
w = z1[ind]

In [56]:
w[0] = 3

In [57]:
w

array([3, 3, 5])

In [58]:
z1

array([1, 3, 5, 7, 9])

In [64]:
c = b[1:]
b[a] is c

False

In [71]:
np.linspace(0,100, 4)

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [72]:
np.logspace(np.log10(10),np.log10(100),10)

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [74]:
X = np.array([[1,2,3] ,[4,5,6]])

In [75]:
X.shape

(2, 3)

In [76]:
X.size

6

In [84]:
rand = np.random.random(10)

In [87]:
np.any(rand > .45)

True

In [89]:
np.all(rand > .2)

False

In [94]:
x = 17
not np.any([x%i == 0 for i in range(2, x)])

True