In [1]:
import numpy as np

In [2]:
def create_board():
    return np.zeros((3,3))

In [3]:
board = create_board()

In [4]:
board

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
def place(board , player , position):
    if board[position] == 0:
        board[position] = player

In [6]:
board = create_board()
place(board , 1 , (0,0))

In [7]:
board

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
def possibility(board):
    free = np.where(board == 0)
    return list(zip(free[0] , free[1]))

In [9]:
choice = possibility(board)

In [10]:
print(choice)

[(0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]


In [11]:
import random
random.seed(1)

In [12]:
def random_choice(board ,player):
    select = possibility(board)
    if len(select) > 0:
        final_s = random.choice(select)
        place(board , player , final_s)
    return board

In [13]:
random_choice(board , 2)

array([[1., 0., 0.],
       [2., 0., 0.],
       [0., 0., 0.]])

In [14]:
random.seed(1)

In [15]:
new_b = create_board()

In [16]:
for i in range(3):
    for player in [1,2]:
        random_choice(new_b , player)

In [17]:
new_b

array([[2., 2., 1.],
       [0., 1., 0.],
       [0., 1., 2.]])